

# Delete DigitalOcean Droplet/Space
- import_tasks: "{{ role_path }}/tasks/delete_server.yml"
  tags: delete-subscription

# Delete AWX Job Templates for Server
- import_tasks: "{{ role_path }}/tasks/delete_awx_templates.yml"
  tags: delete-subscription

# Delete Organisation Directories
- import_tasks: "{{ role_path }}/tasks/delete_server_directory.yml"
  tags: delete-subscription

